INSERT INTO category (id, name, description) VALUES (nextVal('category_seq'), 'Men Clothing', 'Fashion items for men'),
                                                    (nextVal('category_seq'), 'Women Clothing', 'Fashion items for women'),
                                                    (nextVal('category_seq'), 'Shoes', 'Various styles of shoes'),
                                                    (nextVal('category_seq'), 'Accessories', 'Fashion accessories like bags and hats'),
                                                    (nextVal('category_seq'), 'Sportswear', 'Clothing for sports and outdoor activities'),
                                                    (nextVal('category_seq'), 'Casual Wear', 'Everyday casual fashion'),
                                                    (nextVal('category_seq'), 'Formal Wear', 'Business and formal attire'),
                                                    (nextVal('category_seq'), 'Outerwear', 'Jackets, coats, and warm clothing'),
                                                    (nextVal('category_seq'), 'Streetwear', 'Trendy street fashion'),
                                                    (nextVal('category_seq'), 'Luxury Fashion', 'High-end designer fashion');

INSERT INTO product (id, name, description, price, category_id) VALUES
                                                                    (nextval('product_seq'), 'Slim Fit Jeans', 'Stylish slim fit denim jeans for men', 49.99, 1),
                                                                    (nextval('product_seq'), 'Cotton T-Shirt', 'Soft and breathable cotton t-shirt', 19.99, 1),
                                                                    (nextval('product_seq'), 'Leather Jacket', 'Genuine leather biker jacket', 120.50, 351),
                                                                    (nextval('product_seq'), 'Running Shoes', 'Lightweight running shoes for sports', 89.99, 151),
                                                                    (nextval('product_seq'), 'Sneakers', 'Trendy sneakers for casual wear', 75.00, 101),
                                                                    (nextval('product_seq'), 'Maxi Dress', 'Elegant maxi dress for women', 65.99, 51),
                                                                    (nextval('product_seq'), 'Denim Shorts', 'Casual denim shorts for summer', 39.99, 51),
                                                                    (nextval('product_seq'), 'Baseball Cap', 'Classic baseball cap with adjustable strap', 15.00, 151),
                                                                    (nextval('product_seq'), 'Backpack', 'Stylish and spacious backpack', 59.99, 151),
                                                                    (nextval('product_seq'), 'Formal Suit', 'Classic black formal suit for men', 199.99, 301),
                                                                    (nextval('product_seq'), 'Evening Gown', 'Elegant evening gown for special occasions', 299.99, 451),
                                                                    (nextval('product_seq'), 'Hoodie', 'Comfortable cotton hoodie', 45.00, 251),
                                                                    (nextval('product_seq'), 'Sweatpants', 'Soft and cozy sweatpants', 35.00, 251),
                                                                    (nextval('product_seq'), 'Leather Belt', 'Genuine leather belt with metal buckle', 25.99, 151),
                                                                    (nextval('product_seq'), 'Winter Coat', 'Warm and stylish winter coat', 150.00, 351),
                                                                    (nextval('product_seq'), 'Ankle Boots', 'Trendy ankle boots for women', 99.99, 101),
                                                                    (nextval('product_seq'), 'Silk Scarf', 'Luxury silk scarf with elegant design', 55.00, 451),
                                                                    (nextval('product_seq'), 'Jogging Set', 'Comfortable jogging set for workouts', 85.00, 201),
                                                                    (nextval('product_seq'), 'Graphic Tee', 'Cool printed graphic t-shirt', 22.50, 401),
                                                                    (nextval('product_seq'), 'Cargo Pants', 'Durable cargo pants with multiple pockets', 48.99, 401);
