server:
  port: 8020

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb://vsung2608:260804@localhost:27017/cart-service?authSource=admin