server:
  port: 8090

spring:
  data:
    mongodb:
      uri: mongodb://vsung2608:260804@localhost:27017/customer-service?authSource=admin

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO  # Mức log chung
    org.springframework.web: DEBUG  # Log cho Spring Web (REST API)
    org.springframework.cloud.gateway: DEBUG  # Log chi tiết cho Gateway
    org.springframework.http.server: DEBUG  # Log request & response
    org.springframework.security: DEBUG  # Log bảo mật (nếu dùng Spring Security)
    org.apache.kafka: DEBUG  # Log Kafka (nếu dùng Kafka)
    com.rabbitmq: DEBUG  # Log RabbitMQ (nếu dùng RabbitMQ)

management:
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: customer-service

otel:
  exporter:
    otlp:
      endpoint: http://grafana-tempo:4317
  traces:
    exporter: otlp
